### ISSUE TITLE
Constant "ArrayChannel was cancelled"

### ISSUE THREAD

**Issue by dopefull1** [Gaming32/world-host-server-kotlin#1]
My friend and I both tried to add each other, but when we do it still says 0 friends. We have both tried to host a single-player world, but nothing shows up in the "friends" tab - even though everything appears to work normally as it displays the port number in chat. Clicking refresh a couple times did not help. 

(Their name is censored btw)
![unknown_2023 03 13-10 33](https://user-images.githubusercontent.com/57564419/224663173-787b9157-1ab8-45b7-9c3d-c6602b1be981.png)
![unknown_2023 03 13-10 30](https://user-images.githubusercontent.com/57564419/224663179-e1050812-ede4-44f9-860a-8f3ea48142ec.png)

**Comment by Gaming32** [comment]
Being worked on in #2

**Comment by Gaming32** [comment]
Fixed in #2

**Comment by dopefull1** [comment]
Thank you very much for your work. I can confirm it works flawlessly now.
