### ISSUE TITLE
In depth tutorial on self hosting it please

### ISSUE THREAD

**Issue by CornetPanique86** [Gaming32/world-host-server-kotlin#5]
Can you make a detailed tutorial on setting up the server.
I have an Ubuntu VPS and I am confused on how to set it up, as well as the DNS.

Right now, I executed 
`java -jar ./world-host-server-kotlin-all.jar --baseAddr "wh.example.com"`

And have a CName record with value: `*.wh` and Target: `wh.example.com`

In-game, it fails to connect to the server `wh.example.com`.

**Comment by Gaming32** [comment]
Your server setup seems correct. Can you send client logs?

**Comment by CornetPanique86** [comment]
I fixed it after allowing port 9646: `ufw allow 9646` 🙂 thank you!
